#' @exportClass tbl_xdf
#' @export tbl_xdf
tbl_xdf <- setClass("tbl_xdf", contains="RxXdfData", slots=c(hasTblFile="logical"))


setMethod("initialize", "tbl_xdf", function(.Object, xdf=NULL, file=NULL, createCompositeSet=NULL, ...) {
    fileSystem <- rxGetFileSystem(xdf)
    if(is.null(createCompositeSet))
        createCompositeSet <- isCompositeXdf(xdf)

    if(is.null(file))
    {
        tmpdir <- get_dplyrxdf_dir(fileSystem)
        if(!createCompositeSet)
            file <- tempfile(tmpdir=tmpdir, fileext=".xdf")
        else file <- tempfile(tmpdir=tmpdir)
    }
    else file <- validateXdfFile(file, createCompositeSet)

    arglst <- rlang::modify(list(.Object, file=file, fileSystem=fileSystem, createCompositeSet=createCompositeSet),
        !!!list(...))
    .Object <- rlang::invoke("callNextMethod", arglst, .env=parent.frame(), .bury=NULL)
    # hasTblFile should really be isDeletable; misnomer is for back-compatibility
    .Object@hasTblFile <- !file.exists(.Object@file)
    .Object
})


setMethod("coerce", list(from="RxFileData", to="tbl_xdf"), function(from, to, strict=TRUE) {
    out <- tbl_xdf(fileSystem=rxGetFileSystem(from))
    rxImport(from, out, rowsPerRead=.dxOptions$rowsPerRead)
})


#' Delete data files for xdf tbls
#'
#' @param path Directory where the files are located. Defaults to the temporary directory where dplyrXdf creates tbl files (the R temporary directory for the native filesystem, or the dplyrXdf-created directory on HDFS).
#' @details
#' This is a utility function to delete the files generated by dplyrXdf. Note that all xdf files in the specified location will be removed!
#' @export
delete_xdf_tbls <- function(path, fileSystem=rxGetFileSystem())
{
    if(inherits(fileSystem, "RxNativeFileSystem"))
    {
        if(missing(path))
            path <- get_dplyrxdf_dir("native")
        files <- dir(path, pattern="\\.xdf$", full.names=TRUE, ignore.case=.Platform$OS.type == "windows")
        # use unlink to allow for the possibility of composite xdfs
        unlink(files, recursive=TRUE)
    }
    else if(inherits(fileSystem, "RxHdfsFileSystem"))
    {
        if(missing(path))
            path <- get_dplyrxdf_dir("hdfs")
        # rxHadoopFileExists doesn't always exist, duplicate its functionality
        pathExists <- (path == .dxOptions$hdfsWorkDir && .dxOptions$hdfsWorkDirCreated) ||
            (rxHadoopCommand(paste0("fs -test -e '", path, "'"), intern=FALSE) == 0)
        if(pathExists)
        {
            files <- rxHadoopListFiles(path, intern=TRUE)
            files <- substr(files, regexpr("\\s[[:alnum:][:punct:]]*$", files) + 1, nchar(files))
            files <- grep("xdfTBl", files, value=TRUE)
            lapply(files, rxHadoopRemoveDir, skipTrash=TRUE, intern=TRUE)
        }
    }
    invisible(NULL)
}

