#' @exportClass tbl_xdf
#' @export tbl_xdf
tbl_xdf <- setClass("tbl_xdf", contains="RxXdfData", slots=c(hasTblFile="logical"))


setMethod("initialize", "tbl_xdf", function(.Object, xdf=NULL, file=NULL, ...) {
    if(is.null(file))
        file <- tempfile(tmpdir=getXdfTblDir(), fileext=".xdf")
    fileSystem <- rxGetFileSystem(xdf)

    .Object <- callNextMethod(.Object, file=file, fileSystem=fileSystem)
    .Object@hasTblFile <- TRUE
    .Object
})


setMethod("coerce", list(from="RxFileData", to="tbl_xdf"), function(from, to, strict=TRUE) {
    out <- tbl_xdf(from)
    rxImport(from, out, rowsPerRead=.dxOptions$rowsPerRead)
})


#' Delete data files for xdf tbls
#'
#' @param path Directory where the files are located. Defaults to the temporary directory where dplyrXdf creates tbl files (the R temporary directory for the native filesystem, or the dplyrXdf-created directory on HDFS).
#' @details
#' This is a utility function to delete the files generated by dplyrXdf. Note that all xdf files in the specified location will be removed!
#' @export
deleteXdfTbls <- function(path, fileSystem=rxGetFileSystem())
{
    if(inherits(fileSystem, "RxNativeFileSystem"))
    {
        if(missing(path))
            path <- getXdfTblDir("native")
        files <- dir(path, pattern="\\.xdf$", full.names=TRUE, ignore.case=.Platform$OS.type == "windows")
        # use unlink to allow for the possibility of composite xdfs
        unlink(files, recursive=TRUE)
    }
    else if(inherits(fileSystem, "RxHdfsFileSystem"))
    {
        if(missing(path))
            path <- getXdfTblDir("hdfs")
        # rxHadoopFileExists doesn't always exist, duplicate its functionality
        pathExists <- (path == .dxOptions$hdfsWorkDir && .dxOptions$hdfsWorkDirCreated) ||
            (rxHadoopCommand(paste0("fs -test -e '", path, "'"), intern=FALSE) == 0)
        if(pathExists)
        {
            files <- rxHadoopListFiles(path, intern=TRUE)
            files <- substr(files, regexpr("\\s[[:alnum:][:punct:]]*$", files) + 1, nchar(files))
            files <- grep("xdfTBl", files, value=TRUE)
            lapply(files, rxHadoopRemoveDir, skipTrash=TRUE, intern=TRUE)
        }
    }
    invisible(NULL)
}

