#' Get and set the xdf tbl directory
#'
#' By default, dplyrXdf will save the xdf files it creates in the R temporary directory. This can be a problem if it is in a location with limited disk space. Use \code{set_dplyrxdf_dir} to change the xdf tbl directory, and \code{get_dplyrxdf_dir} to view it.
#'
#' @param path Location in which to save xdf tbls. If missing, defaults to the R temporary directory.
#' @param fileSystem The filesystem for which to set or get the tbl directory; can be either "hdfs" or "native". Currently only the native (local) filesystem is supported.
#'
#' @details
#' If \code{path} is supplied, \code{set_dplyrxdf_dir} creates a new directory (with a unique name) located \emph{under} \code{path}. This ensures that the files managed by dplyrXdf are properly isolated from the rest of the filesystem.
#'
#' @seealso
#' \code{\link{rxGetFileSystem}}, \code{\link{rxSetFileSystem}}
#' @rdname workdir
#' @export
set_dplyrxdf_dir <- function(path, fileSystem=rxGetFileSystem())
{
    fileSystem <- validateFileSystem(fileSystem)
    if(inherits(fileSystem, "RxHdfsFileSystem"))
    {
        if(missing(path))
            path <- gsub("\\", "/", tempfile(pattern="dxTmp", tmpdir="/tmp"), fixed=TRUE)
        .dxOptions$hdfsWorkDir <- path
        .dxOptions$hdfsWorkDirCreated <- FALSE
    }
    else
    {
        if(missing(path))
            path <- tempdir()
        path <- tempfile(pattern="dxTmp", tmpdir=path)
        path <- normalizePath(path, mustWork=FALSE)
        dir.create(path, recursive=TRUE)
        .dxOptions$localWorkDir <- path
    }
    invisible(NULL)
}


#' @rdname workdir
#' @export
get_dplyrxdf_dir <- function(fileSystem=rxGetFileSystem())
{
    fileSystem <- validateFileSystem(fileSystem)
    if(isHdfs(fileSystem))
        .dxOptions$hdfsWorkDir
    else .dxOptions$localWorkDir
}


make_dplyrxdf_dir <- function(fileSystem=rxGetFileSystem())
{
    fileSystem <- validateFileSystem(fileSystem)
    if(isHdfs(fileSystem))
    {
        path <- .dxOptions$hdfsWorkDir
        if(!rxHadoopFileExists(path))
            res <- rxHadoopMakeDir(path)
        if(res)
        {
            .dxOptions$hdfsWorkDirCreated <- TRUE
        }
        else warning("unable to create HDFS working directory", call.=FALSE)
        return(res)
    }
    else
    {
        path <- .dxOptions$localWorkDir
        if(!dir.exists(path))
            return(dir.create(path))
    }
    NULL
}


#' Delete data files for xdf tbls
#'
#' @param fileSystem Filesystem on which to delete the xdf tbls.
#' @details
#' This is a utility function to delete the files generated by dplyrXdf. Note that all xdf files in the specified location will be removed!
#' @rdname workdir
#' @export
clean_dplyrxdf_dir <- function(fileSystem=rxGetFileSystem())
{
    if(inherits(fileSystem, "RxNativeFileSystem"))
    {
        path <- get_dplyrxdf_dir("native")
        files <- dir(path, full.names=TRUE)
        # use unlink to allow for the possibility of composite xdfs
        unlink(files, recursive=TRUE)
    }
    else if(inherits(fileSystem, "RxHdfsFileSystem"))
    {
        path <- get_dplyrxdf_dir("hdfs")
        # rxHadoopFileExists doesn't always exist, duplicate its functionality
        pathExists <- (path == .dxOptions$hdfsWorkDir && .dxOptions$hdfsWorkDirCreated) ||
            (rxHadoopCommand(paste0("fs -test -e '", path, "'"), intern=FALSE) == 0)
        if(pathExists)
        {
            files <- rxHadoopListFiles(path, intern=TRUE)
            files <- substr(files, regexpr("\\s[[:alnum:][:punct:]]*$", files) + 1, nchar(files))
            lapply(files, rxHadoopRemoveDir, skipTrash=TRUE, intern=TRUE)
        }
    }
    invisible(NULL)
}


validateFileSystem <- function(fs)
{
    if(!inherits(fs, "RxFileSystem"))
    {
        if(fs == "hdfs")
            fs <- RxHdfsFileSystem()
        else fs <- RxNativeFileSystem()
    }
    fs
}



